Actions:

  # actions with no corresponding API
  - Name: aco-automation:AssociateAccounts
  - Name: aco-automation:CreateAutomationRule
  - Name: aco-automation:DeleteAutomationRule
  - Name: aco-automation:DisassociateAccounts
  - Name: aco-automation:GetAutomationEvent
  - Name: aco-automation:GetAutomationRule
  - Name: aco-automation:GetEnrollmentConfiguration
  - Name: aco-automation:ListAccounts
  - Name: aco-automation:ListAutomationEventSteps
  - Name: aco-automation:ListAutomationEventSummaries
  - Name: aco-automation:ListAutomationEvents
  - Name: aco-automation:ListAutomationRulePreview
  - Name: aco-automation:ListAutomationRulePreviewSummaries
  - Name: aco-automation:ListAutomationRules
  - Name: aco-automation:ListRecommendedActionSummaries
  - Name: aco-automation:ListRecommendedActions
  - Name: aco-automation:ListTagsForResource
  - Name: aco-automation:RollbackAutomationEvent
  - Name: aco-automation:StartAutomationEvent
  - Name: aco-automation:TagResource
  - Name: aco-automation:UntagResource
  - Name: aco-automation:UpdateAutomationRule
  - Name: aco-automation:UpdateEnrollmentConfiguration
