Actions:

  # actions with no corresponding API
  - Name: airflow-serverless:CreateWorkflow
  - Name: airflow-serverless:DeleteWorkflow
  - Name: airflow-serverless:GetTaskInstance
  - Name: airflow-serverless:GetWorkflow
  - Name: airflow-serverless:GetWorkflowRun
  - Name: airflow-serverless:ListTagsForResource
  - Name: airflow-serverless:ListTaskInstances
  - Name: airflow-serverless:ListWorkflowRuns
  - Name: airflow-serverless:ListWorkflowVersions
  - Name: airflow-serverless:ListWorkflows
  - Name: airflow-serverless:StartWorkflowRun
  - Name: airflow-serverless:StopWorkflowRun
  - Name: airflow-serverless:TagResource
  - Name: airflow-serverless:UntagResource
  - Name: airflow-serverless:UpdateWorkflow
