Actions:
  - Name: appconfig:CreateApplication
  - Name: appconfig:CreateConfigurationProfile
  - Name: appconfig:CreateDeploymentStrategy
  - Name: appconfig:CreateEnvironment
  - Name: appconfig:CreateHostedConfigurationVersion
  - Name: appconfig:DeleteApplication
  - Name: appconfig:DeleteConfigurationProfile
  - Name: appconfig:DeleteDeploymentStrategy
  - Name: appconfig:DeleteEnvironment
  - Name: appconfig:DeleteHostedConfigurationVersion
  - Name: appconfig:GetApplication
  - Name: appconfig:GetConfiguration
  - Name: appconfig:GetConfigurationProfile
  - Name: appconfig:GetDeployment
  - Name: appconfig:GetDeploymentStrategy
  - Name: appconfig:GetEnvironment
  - Name: appconfig:GetHostedConfigurationVersion
  - Name: appconfig:GetLatestConfiguration
  - Name: appconfig:ListApplications
  - Name: appconfig:ListConfigurationProfiles
  - Name: appconfig:ListDeploymentStrategies
  - Name: appconfig:ListDeployments
  - Name: appconfig:ListEnvironments
  - Name: appconfig:ListHostedConfigurationVersions
  - Name: appconfig:ListTagsForResource
  - Name: appconfig:StartConfigurationSession
  - Name: appconfig:StartDeployment
  - Name: appconfig:StopDeployment
  - Name: appconfig:TagResource
  - Name: appconfig:UntagResource
  - Name: appconfig:UpdateApplication
  - Name: appconfig:UpdateConfigurationProfile
  - Name: appconfig:UpdateDeploymentStrategy
  - Name: appconfig:UpdateEnvironment
  - Name: appconfig:ValidateConfiguration
