Actions:
  - Name: route53-recovery-control-config:CreateCluster
  - Name: route53-recovery-control-config:CreateControlPanel
  - Name: route53-recovery-control-config:CreateRoutingControl
  - Name: route53-recovery-control-config:CreateSafetyRule
  - Name: route53-recovery-control-config:DeleteCluster
  - Name: route53-recovery-control-config:DeleteControlPanel
  - Name: route53-recovery-control-config:DeleteRoutingControl
  - Name: route53-recovery-control-config:DeleteSafetyRule
  - Name: route53-recovery-control-config:DescribeCluster
  - Name: route53-recovery-control-config:DescribeControlPanel
  - Name: route53-recovery-control-config:DescribeRoutingControl
  - Name: route53-recovery-control-config:DescribeSafetyRule
  - Name: route53-recovery-control-config:ListAssociatedRoute53HealthChecks
  - Name: route53-recovery-control-config:ListClusters
  - Name: route53-recovery-control-config:ListControlPanels
  - Name: route53-recovery-control-config:ListRoutingControls
  - Name: route53-recovery-control-config:ListSafetyRules
  - Name: route53-recovery-control-config:ListTagsForResource
  - Name: route53-recovery-control-config:TagResource
  - Name: route53-recovery-control-config:UntagResource
  - Name: route53-recovery-control-config:UpdateControlPanel
  - Name: route53-recovery-control-config:UpdateRoutingControl
  - Name: route53-recovery-control-config:UpdateSafetyRule

  # actions with no corresponding API
  - Name: route53-recovery-control-config:DescribeRoutingControlByName
