name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: update jq
        run: |
          sudo curl -L -o /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo chmod +x /usr/bin/jq
          jq -V

      - name: Run it
        run: go run main.go -- generate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Report
        run: git add . && git diff
